task_2-user/design_portal/design/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='home'),  # Главная страница
    path('register/', views.RegisterUser.as_view(), name='register'),  # Регистрация
    path('login/', views.LoginUser.as_view(), name='login'),  # Вход
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),  # Каталог
    path('confirm-email/<str:uidb64>/<str:token>/', views.UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email-confirmed/', views.EmailConfirmedView.as_view(), name='email_confirmed'),
    path('confirm-email-failed/', views.EmailConfirmationFailedView.as_view(), name='email_confirmation_failed'),
]

task_2-user/design_portal/design_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('registration/', include('design.urls')),  # Подключаем urls из приложения design
    path('', RedirectView.as_view(url='/registration/')),
    path('order/', include('orders.urls', namespace="order")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task_2-user/design_portal/orders/urls.py
from django.urls import path
from . import views

app_name = "order"

urlpatterns = [
    path('list/', views.OrderListView.as_view(), name='list'),
    path('create/', views.OrderCreateView.as_view(), name='create'),
    path('delete/<int:pk>/', views.DeleteOrderView.as_view(), name='delete')
]

task_2-user/design_portal/orders/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Order(models.Model):
    class ChoicesStatus(models.TextChoices):
        NEW = 'Новая', "NEW"
        ACCEPT = 'Принято', 'ACCEPT'
        DONE = 'Выполнено', 'DONE'

    title = models.CharField(max_length=100)
    description = models.TextField()
    status = models.CharField(
        max_length=50,
        choices=ChoicesStatus.choices,
        default=ChoicesStatus.NEW,
        verbose_name='Статус заказа'
    )
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name='orders'
    )
    time_create = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Время создания"
    )

    objects = models.Manager()

    def __str__(self):
        return self.user.username  # type: ignore

    class Meta:
        verbose_name = 'Заказы'
        verbose_name_plural = 'Заказы'
        ordering = ['-time_create']
        indexes = [
            models.Index(fields=['-time_create'])
        ]


class OrderPhoto(models.Model):
    order = models.ForeignKey(
        'Order',
        on_delete=models.CASCADE,
        related_name='photos',
        verbose_name='Заказ'
    )
    photo = models.ImageField(
        'Фотография заказа',
        upload_to='order_photos/'
    )

    def __str__(self):
        return f"Фото для заказа #{self.order.id}"  # type: ignore

task_2-user/design_portal/orders/forms.py
from django import forms

from .models import Order


class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True  # Разрешаем множественный выбор файлов


class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput()) # Автоматически наследует виджет
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None): # data - входные данные, файлы загруженные через форму
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)): # Если передан список файлов
            result = [single_file_clean(d, initial) for d in data]
        else:  # Если один файл
            result = single_file_clean(data, initial)
        return result


class CreateOrderForm(forms.ModelForm):
    photos = MultipleFileField( # Виджет был создан при помощи комбинации ClearableFileInput и FileField
        required=False,
        widget=MultipleFileInput(attrs={'multiple': True})
    )

    class Meta:
        model = Order
        fields = ['title', 'description']  # Поля из модели Order

    def clean_photos(self):
        photos = self.cleaned_data.get('photos', [])
        len_photos = len(photos)
        if len_photos > 3 or len_photos == 0:  # Проверяем, что загружено не больше трёх файлов
            raise forms.ValidationError("Вы можете загрузить не более 3 фотографий и не должно быть пустой")
        for photo in photos:
            if photo.size > 2 * 1024 * 1024:  # Ограничение размера файла до 2 МБ
                raise forms.ValidationError("Размер каждого изображения не должен превышать 2 МБ.")
        return photos

task_2-user/design_portal/orders/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView

from .forms import CreateOrderForm
from .models import Order, OrderPhoto


class OrderListView(LoginRequiredMixin, ListView):
    model = Order
    template_name = 'orders/order_list.html'  # шаблон для отображения списка
    context_object_name = 'orders'

    def get_queryset(self):
        """
        Возвращает заказы текущего пользователя.
        """
        return Order.objects.filter(user=self.request.user)


class OrderCreateView(LoginRequiredMixin, CreateView):
    template_name = 'orders/create_order.html'
    form_class = CreateOrderForm
    success_url = reverse_lazy('order:list')

    def form_valid(self, form):
        order = form.save(commit=False)
        order.user = self.request.user
        order.save()

        photos = form.cleaned_data.get('photos')
        if photos:
            for photo in photos:
                OrderPhoto.objects.create(order=order, photo=photo)

        return super().form_valid(form)


class DeleteOrderView(LoginRequiredMixin, DeleteView):
    model = Order
    template_name = 'orders/confirm_delete.html'  # Укажите шаблон для подтверждения удаления
    success_url = reverse_lazy('order:list')  # URL для перенаправления после успешного удаления

    def get_queryset(self):
        """
        Ограничиваем доступ к удалению только для заказов текущего пользователя.
        """
        return super().get_queryset().filter(user=self.request.user)

    def post(self, request, *args, **kwargs):
        """
        Переопределяем метод post для проверки статуса перед удалением.
        """
        order = self.get_object()
        if order.status in ['Принято', 'Выполнено']:
            return HttpResponseForbidden("Удаление запрещено.")
        return super().post(request, *args, **kwargs)

task_2-user/design_portal/orders/templates/orders/confirm_delete.html
{% extends 'base_generic.html' %}

{% block content %}
  <h2>Вы уверены, что хотите удалить заказ?</h2>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Удалить</button>
    <a href="{% url 'order:list' %}">Отмена</a>
  </form>
{% endblock %}

task_2-user/design_portal/orders/templates/orders/create_order.html
{% extends "base_generic.html" %}

{% block content %}
<div class="content">
    <form method="post" class="form-container" enctype="multipart/form-data">
    <h3>Регистрация</h3>
        {% csrf_token %}
        {{ form.as_p }}
        <button class="" type="submit">Оформить заказ</button>
    </form>
</div>
{% endblock %}

task_2-user/design_portal/orders/templates/orders/list_tags.html
<h2>Последние выполненные заказы</h2>
<ul>
    {% for order in orders %}
        <li>
            <p><strong>Временная метка:</strong> {{ order.time_create }}</p>
            <p><strong>Название:</strong> {{ order.title }}</p>
            <p><strong>Категория заявки:</strong> {{ order.description }}</p>
            {% if order.photos %}
                {% for photo in order.photos.all|slice:":3" %}
                    <img src="{{ photo.photo.url }}" alt="Фото заявки" style="max-width: 200px;">
                {% endfor %}
            {% else %}
                <p>Фото отсутствует</p>
            {% endif %}
        </li>
    {% endfor %}
</ul>

<h2>Счетчики</h2>
<p><strong>Количество заявок в статусе "Принято в работу":</strong> {{ accepted_count }}</p>

task_2-user/design_portal/orders/templates/orders/order_list.html
{% extends 'base_generic.html' %}

{% block content %}
  <div class="orders-container">
    <h2>Ваши заказы</h2>
    {% for order in orders %}
      <div class="order-item">
        <h3>Название заказа: {{ order.title }}</h3>
        <p>Описание заказа: {{ order.description }}</p>
        <p>Статус заказа: {{ order.status }}</p>
        <p>Время создания: {{ order.time_create }}</p>

        <div class="order-photos">
          {% for photo in order.photos.all|slice:":3" %}
            <img src="{{ photo.photo.url }}" alt="Фото заявки" style="max-width: 200px;">
          {% endfor %}
        </div>

        <a href="{% url 'order:delete' order.pk %}">Удалить</a>
      </div>
    {% endfor %}
  </div>
{% endblock %}