task_2-user/design_portal/design/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='home'),  # Главная страница
    path('register/', views.RegisterUser.as_view(), name='register'),  # Регистрация
    path('login/', views.LoginUser.as_view(), name='login'),  # Вход
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),  # Каталог
    path('confirm-email/<str:uidb64>/<str:token>/', views.UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email-confirmed/', views.EmailConfirmedView.as_view(), name='email_confirmed'),
    path('confirm-email-failed/', views.EmailConfirmationFailedView.as_view(), name='email_confirmation_failed'),
]

task_2-user/design_portal/design_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('registration/', include('design.urls')),  # Подключаем urls из приложения design
    path('', RedirectView.as_view(url='/registration/')),
    path('order/', include('orders.urls', namespace="order")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task_2-user/design_portal/orders/urls.py
from django.urls import path
from . import views

app_name = "order"

urlpatterns = [
    path('list/', views.OrderListView.as_view(), name='list'),
    path('create/', views.OrderCreateView.as_view(), name='create'),
    path('delete/<int:pk>/', views.DeleteOrderView.as_view(), name='delete')
]

task_2-user/design_portal/design/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    username = models.CharField(max_length=100, verbose_name='Имя пользователя', unique=True)
    email = models.EmailField(max_length=100, verbose_name='Email', unique=True)
    consent_data = models.BooleanField("Согласие на обработку данных", default=False)
    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'

    def __str__(self):
        return self.username

task_2-user/design_portal/design/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .models import CustomUser


class RegisterUserForm(UserCreationForm):
    email = forms.CharField(label="E-mail",
                            widget=forms.EmailInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label="Password",
                                widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label="Reply password",
                                widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2', 'consent_data']
        widgets = {
            'consent_data': forms.CheckboxInput(attrs={'id': 'id_consent'})
        }


class LoginForm(AuthenticationForm):
    password = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['email', 'password']


class Registration(CreateView):
    model = CustomUser  # Укажите модель
    template_name = 'registration/register.html'
    success_url = reverse_lazy('login')  # URL для перенаправления после успешной регистрации
    fields = ['username', 'password', 'email']  # Поля формы

task_2-user/design_portal/design/views.py
from django.contrib.auth import logout, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils.http import urlsafe_base64_decode
from django.views import View
from django.views.generic import CreateView, TemplateView

from .forms import LoginForm, RegisterUserForm
from .utils import send_verification_email, account_activation_token


# Главная страница
def index(request):
    return render(request, 'index.html')


# Регистрация
class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'registration/register.html'
    extra_context = {'title': "Register"}
    success_url = reverse_lazy('login')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        self.request.session['user_email'] = user.email
        send_verification_email(self.request, user)
        return super().form_valid(form)


class UserConfirmEmailView(View):

    def get(self, request, uidb64, token):
        User = get_user_model()
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = get_object_or_404(User, pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            user.save()
            return redirect('email_confirmed')
        else:
            return redirect('email_confirmation_failed')


class EmailConfirmedView(TemplateView):
    template_name = 'registration/email_confirmed.html'
    extra_context = {'title': 'Your email address has been activated'}


class EmailConfirmationFailedView(TemplateView):
    template_name = 'registration/email_confirmation_failed.html'
    extra_context = {'title': 'Invalid link'}


class LoginUser(LoginView):
    form_class = LoginForm
    template_name = 'registration/login.html'
    extra_context = {'title': 'Авторизация'}


# Выход
def logout_view(request):
    logout(request)  # Выход пользователя
    return render(request, 'registration/logout.html')


class ProfileUser(LoginRequiredMixin, TemplateView):
    model = get_user_model()
    template_name = 'registration/profile.html'
    extra_context = {
        'title': "Профиль пользователя",
    }

    def get_success_url(self):
        return reverse_lazy('profile')

    def get_object(self, queryset=None):
        return self.request.user

task_2-user/design_portal/design/templates/base_generic.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DesignPro</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

</head>
<body>
    <nav class="navbar">
        <a class="logo"  href="{% url 'home' %}">DesignPro</a>
        <ul class="nav-links">
            {% if user.is_authenticated %}

              <li><a href="{% url 'profile' %}">Профиль | {{ user.username }}</a></li>
              <li><a href="{% url 'order:list' %}">Мои заказы</a></li>
              <li><a href="{% url 'order:create' %}">Сделать заказ</a></li>
              <li><a href="{% url 'logout' %}"
		   onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Выйти</a>
            <form id="logout-form" method="POST" style="display: none;" action="{% url 'logout' %}">
                {% csrf_token %}
                <button type="submit" class="logout-link">Выйти</button>
            </form></li>
            {% else %}
            <li><a href="{% url 'login' %}">Войти</a></li>
            <li><a href="{% url 'register' %}">Регистрация</a></li>
            {% endif %}
        </ul>
    </nav>
{% block content %}
{% endblock %}
</body>
</html>

task_2-user/design_portal/design/templates/index.html
{% extends "base_generic.html" %}
{% load order_tags %}

{% block content %}

<h1>Design Pro</h1>
<p>Дизайн интерьеров</p>
    {% if user.is_authenticated %}
    {% show_all_tags %}
    {% else %}
    <span> Что бы увидеть свои заказы, Вы должны авторизоваться</span>
    {% endif %}
{% endblock %}